
// src/app/terms/page.tsx
'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="container mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="mb-8">
        <Link href="/" passHref legacyBehavior>
          <Button variant="outline" className="active:scale-95 transition-transform">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
          </Button>
        </Link>
      </div>

      <article className="prose dark:prose-invert max-w-none bg-card p-6 sm:p-8 rounded-lg shadow-lg border">
        <h1 className="text-3xl sm:text-4xl font-bold text-primary mb-6">Terms and Conditions</h1>
        
        <p className="text-muted-foreground mb-6">Last updated: {new Date().toLocaleDateString()}</p>

        <h2 className="text-2xl font-semibold mt-8 mb-3">1. Introduction</h2>
        <p>
          Welcome to NOTO by beasty powered by turri.ai ("Application", "we", "us", or "our"). 
          These Terms and Conditions govern your use of our application. By accessing or using 
          the Application, you agree to be bound by these Terms and Conditions. If you disagree 
          with any part of the terms, then you may not access the Application.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3">2. Use of the Application</h2>
        <p>
          You agree to use the Application only for lawful purposes and in a way that does not 
          infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the 
          Application. Prohibited behavior includes harassing or causing distress or inconvenience 
          to any other user, transmitting obscene or offensive content, or disrupting the normal 
          flow of dialogue within the Application.
        </p>
        <p>
          The Application primarily stores data locally on your device using browser local storage. 
          We are not responsible for any loss of data.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-3">3. AI-Generated Content</h2>
        <p>
          The Application uses generative AI features ("AI Features") provided through Genkit. 
          While we strive to ensure the accuracy and usefulness of content generated by AI Features, 
          we make no warranties or representations regarding its reliability, accuracy, or completeness.
          You acknowledge that AI-generated content may sometimes be inaccurate, incomplete, or offensive.
          You are solely responsible for your use of and reliance on any AI-generated content.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3">4. Intellectual Property</h2>
        <p>
          The Application and its original content (excluding content provided by users or generated by AI based on user input), 
          features, and functionality are and will remain the exclusive property of the Application's creators.
        </p>
        <p>
          You retain all rights to the content you input into the Application. By using the AI features, you grant us a license
          to use your input content solely for the purpose of providing the AI features to you.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3">5. Limitation of Liability</h2>
        <p>
          In no event shall the Application, nor its directors, employees, partners, agents, suppliers, 
          or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, 
          including without limitation, loss of profits, data, use, goodwill, or other intangible losses, 
          resulting from (i) your access to or use of or inability to access or use the Application; 
          (ii) any conduct or content of any third party on the Application; (iii) any content obtained 
          from the Application, including AI-generated content; and (iv) unauthorized access, use, or 
          alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), 
          or any other legal theory, whether or not we have been informed of the possibility of such damage.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3">6. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. 
          If a revision is material, we will try to provide at least 30 days' notice prior to any 
          new terms taking effect. What constitutes a material change will be determined at our 
          sole discretion.
        </p>
        <p>
          By continuing to access or use our Application after those revisions become effective, 
          you agree to be bound by the revised terms. If you do not agree to the new terms, 
          please stop using the Application.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3">7. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us (details to be provided by Application owner).
        </p>
        
        <div className="mt-10 text-center">
          <p className="text-sm text-muted-foreground">
            Thank you for using NOTO!
          </p>
        </div>
      </article>
    </div>
  );
}
